version: '3.9'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src       
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    command: npm start